[project]
name = "practico4-sql-alchemy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tanatzu", email = "tanatzu1@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "sqlalchemy>=2.0.53",
]

[project.scripts]
practico4-sql-alchemy = "practico4_sql_alchemy:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
